## Implementation Using Scikit-Learn

In [30]:
import pandas as pd
import numpy as np

In [18]:
train_x = pd.read_csv('Data_Science_London_dataset(Kaggle)/train.csv')
train_y = pd.read_csv('Data_Science_London_dataset(Kaggle)/trainLabels.csv')
test_dataset = pd.read_csv('Data_Science_London_dataset(Kaggle)/test.csv')
train_x.head()

,0.29940251144353242,-1.2266241875260637,1.4984250500215328,-1.1761503610375272,5.2898525545597037,0.20829711393323402,2.4044983672405826,1.5945062220589785,-0.051608163273514231,0.66323431039687908,...,-0.85046544625016463,-0.62298999638261954,-1.8330573433160038,0.29302438506869571,3.5526813410266507,0.71761099417552265,3.3059719748508889,-2.7155588147154619,-2.6824085866346223,0.10105047232890663
0,-1.174176,0.332157,0.949919,-1.285328,2.199061,-0.151268,-0.427039,2.619246,-0.765884,-0.093780,...,-0.819750,0.012037,2.038836,0.468579,-0.517657,0.422326,0.803699,1.213219,1.382932,-1.817761
1,1.192222,-0.414371,0.067054,-2.233568,3.658881,0.089007,0.203439,-4.219054,-1.184919,-1.240310,...,-0.604501,0.750054,-3.360521,0.856988,-2.751451,-1.582735,1.672246,0.656438,-0.932473,2.987436
2,1.573270,-0.580318,-0.866332,-0.603812,3.125716,0.870321,-0.161992,4.499666,1.038741,-1.092716,...,1.022959,1.275598,-3.480110,-1.065252,2.153133,1.563539,2.767117,0.215748,0.619645,1.883397
3,-0.613071,-0.644204,1.112558,-0.032397,3.490142,-0.011935,1.443521,-4.290282,-1.761308,0.807652,...,0.513906,-1.803473,0.518579,-0.205029,-4.744566,-1.520015,1.830651,0.870772,-1.894609,0.408332
4,-0.773247,-0.123227,0.047423,-0.210266,10.377793,0.526604,-2.751616,0.315541,0.608603,-0.043421,...,-1.487714,0.792790,-0.540711,0.114115,-0.277477,-0.896411,-2.805207,0.469162,3.614157,0.081689

In [19]:
train_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 40 columns):
0.29940251144353242      999 non-null float64
-1.2266241875260637      999 non-null float64
1.4984250500215328       999 non-null float64
-1.1761503610375272      999 non-null float64
5.2898525545597037       999 non-null float64
0.20829711393323402      999 non-null float64
2.4044983672405826       999 non-null float64
1.5945062220589785       999 non-null float64
-0.051608163273514231    999 non-null float64
0.66323431039687908      999 non-null float64
-1.4083700642531511      999 non-null float64
1.1147436351160869       999 non-null float64
0.91041530967390116      999 non-null float64
2.2181103179158135       999 non-null float64
4.3056427290235391       999 non-null float64
0.088923978050666208     999 non-null float64
0.1691492586690862       999 non-null float64
0.41344763764684195      999 non-null float64
1.5138621708864943       999 non-null float64
2.6629665829474161       999 non-null float64
-1.0727654812214888      999 non-null float64
0.14911112051014644      999 non-null float64
0.55957919164070269      999 non-null float64
4.3788846423749064       999 non-null float64
-0.4636026556416834      999 non-null float64
-0.063959155289009084    999 non-null float64
0.54493030536966891      999 non-null float64
0.71277166708074502      999 non-null float64
-1.4940501263538932      999 non-null float64
-2.6361688752136554      999 non-null float64
-0.85046544625016463     999 non-null float64
-0.62298999638261954     999 non-null float64
-1.8330573433160038      999 non-null float64
0.29302438506869571      999 non-null float64
3.5526813410266507       999 non-null float64
0.71761099417552265      999 non-null float64
3.3059719748508889       999 non-null float64
-2.7155588147154619      999 non-null float64
-2.6824085866346223      999 non-null float64
0.10105047232890663      999 non-null float64
dtypes: float64(40)
memory usage: 312.3 KB

In [20]:
train_y.head()

   1
0  0
1  0
2  1
3  0
4  1

In [21]:
print(train_x.shape)
print(train_y.shape)

(999, 40)
(999, 1)

In [31]:
from sklearn.model_selection import train_test_split

In [35]:
train_tr_x,test_tr_x=train_test_split(train_x,test_size=0.3)
train_tr_y,test_tr_y=train_test_split(train_y,test_size=0.3)